web_django/learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # 先匹配users/，进入users.urls继续匹配
    path('users/', include('users.urls')),
    # '' -> localhost
    path('', include('learning_logs.urls')),
]

web_django/learning_log/learning_logs/urls.py
"""定义learning_logs的url模式"""
from django.urls import URLPattern, path, include
from . import views

app_name = 'learning_logs'

"""
为每个试图定义url：path('url', 'view', '别名')
识别到匹配的url，调用相应的view
"""
urlpatterns = [
    path('', views.index, name='index'),  # 主页
    path('topics/', views.topics, name='topics'),  # 主题列表
    path('topic/<int:topic_id>/', views.topic, name='topic'),  # 特定主题
    path('new_topic/', views.new_topic, name='new_topic'),  # 新建主题
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),  # 新建条目
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),  # 修改条目

]

web_django/learning_log/users/urls.py
"""定义users的url模式"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # 包含默认的身份验证url
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register')
]

web_django/learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)  # 储存用户写的主题
    date_added = models.DateTimeField(auto_now_add=True)  # 自动标记文件创建时的时间
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


class Entry(models.Model):
    """学到有关某个主题的相关知识"""
    # 让每条数据关联到特定的Topic，CASCADE指删除Topic时条目一起删除
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        """用于储存额外数据"""
        # 使用entries展示多个条目，默认为entrys
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示"""
        # 只展示前50个字符
        if(len(self.text) > 50):
            return f"{self.text[:50]}..."
        else:
            return self.text[:50]

web_django/learning_log/users/models.py
from django.db import models

# Create your models here.

web_django/learning_log/learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

web_django/learning_log/learning_logs/views.py
from django.http import Http404
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.


def index(request):
    """学习笔记的主页"""
    return render(request, 'learning_logs/index.html')


@login_required  # 检查用户登陆后，才继续运行下面代码
def topics(request):
    """显示所有主题"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required  # 检查用户登陆后，才继续运行下面代码
def topic(request, topic_id):
    """显示特定主题"""
    topic = get_object_or_404(Topic, id=topic_id)
    # 确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required  # 检查用户登陆后，才继续运行下面代码
def new_topic(request):
    """新建主题"""
    if request.method != 'POST':
        # 未提交数据，创建新表单
        form = TopicForm()
    else:
        # POST提交了数据，处理数据
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required  # 检查用户登陆后，才继续运行下面代码
def new_entry(request, topic_id):
    """新建条目"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # 未提交数据，创建新表单
        form = EntryForm()
    else:
        # POST提交了数据，对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)  # 暂存在new_entry中，不提交到数据库中
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required  # 检查用户登陆后，才继续运行下面代码
def edit_entry(request, entry_id):
    """编辑条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

web_django/learning_log/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def register(request):
    if request.method != 'POST':
        form = UserCreationForm
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user) # 自动登录
            return redirect('learning_logs:index')
    context = {'form': form}
    return render(request, 'registration/register.html', context)

web_django/learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meat name="viewport" content="width=devide-width, initial-scale=1, shrink-to-fit=no">
    <titel>Learning Log</titel>
    
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <!-- nav元素：包括 navbar 和 navbar-expend-me 样式，light指浅色，mb指margin-botton下边距，border指加一个边界 -->

        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
        <!-- 主页链接，navbar-brand 样式 -->
        
        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
        <!-- 导航栏按钮，太窄时显示 -->

        <div class="collapse navbar-collapse" id="navbarCollapse">
        <!-- 定义导航栏的位置、左侧内容，ul指列表，此处只有一项topics -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
                </li>
            </ul>
            
            <ul class="navbar-nav ml-auto"> <!--- ml-auto->左边距自动(靠右) -->
                {% if user.is_authenticated %} 
                <!--登陆了，展示问候语和注销-->
                    <li class="nav-item">
                        <span class="navbar-text">Hello,{{ user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %} 
                <!--没登陆，展示注册和登陆-->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
    <!--页面主体，container样式-->
        <div class="pb-2 mb-2 border-bottom">
        <!--标题，pd内边距，mb外边距，下边框-->
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
        <!--内容-->
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>

</html>

web_django/learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html"  %}
{% load bootstrap4 %}

{% block page_header %}
    <h1><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h1>
{% endblock page_header %}

{% block content %}

    <h5>Edit entry:</h5>

    <form class="form" action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button class="btn btn-primary" name="submit">Save changrs</button>
        {% endbuttons %}
    </form>

{% endblock content %}

web_django/learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Track your learning.</h1>
        <!--display-3更窄更高-->

        <p class="lead">Make your own Learning Log, and keep a list of the
            topic you're learning about. Whenever you learn something new
            about a topic, make an entry summarizing what you've learned.
        </p>
        
        <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topics' %}"
            role="button">Start &raquo;</a>
        <!--注册按钮 &raquo两个箭头-->
    </div>
{% endblock page_header %}

web_django/learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h1><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h1>
{% endblock page_header %}

{% block content %}
    <h5>Add a new entry:</h5>
    <form class="form" action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button class="btn btn-primary" name='submit'>Add entry</button>
        {% endbuttons %}
    </form>
{% endblock content %}

web_django/learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>Add a new topic:</h1>
{% endblock page_header %}

{% block content %}
    <form class="form" action="{% url 'learning_logs:new_topic' %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button class="btn btn-primary" name="submit">Add topic</button>
        {% endbuttons %}
    </form>
{% endblock content %}

web_django/learning_log/learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <h1>{{ topic }}</h1>
{% endblock page_header %}

{% block content %}
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
    </p>

    {% for entry in entries %}
        <div class="card mb-3">
            <h5 class="card-header">
                {{ entry.date_added|date:'Y M d, H:i' }}
                <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a></small>
            </h5>
            
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <li>无</li>
    {% endfor %}

{% endblock content %}

web_django/learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
    <ul>
        {% for topic in topics %}
            <li>
                <h4><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h4>
            </li>
        {% empty %}
            <li><h4>No topics have been added yet.</h4></li>
        {% endfor %}
    </ul>

    <h5><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h5>
{% endblock content %}